# Generated by Django 6.0.3 on 2026-03-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('prix', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('isbn', models.CharField(default='0', max_length=11)),
            ],
        ),
    ]
